import type { QuoteCurrency, TimestampMs, VenueId, VenueQuote } from '@jet/shared';

export interface VenueAdapter {
  readonly venueId: VenueId;
  readonly quote: QuoteCurrency;
  /** All quotes generated by this venue in [from, to] (inclusive on both ends). */
  samplesBetween(from: TimestampMs, to: TimestampMs): VenueQuote[];
  /** Most recent quote observable at `ts` (accounts for venue latency). Null if before market start. */
  latestAt(ts: TimestampMs): VenueQuote | null;
}
